Updates

diff --git a/.github/workflows/create_github_release.yaml b/.github/workflows/create_github_release.yaml
--- a/.github/workflows/create_github_release.yaml
+++ b/.github/workflows/create_github_release.yaml
@@ -9,8 +9,8 @@ on:
         type: string
 
 jobs:
-  generate_artifacts:
-    name: Generate artifacts
+  generate_extractor_artifact:
+    name: Generate extractor artifact
     strategy:
       matrix:
         dotnet-runtime: [linux-x64, win-x64]
@@ -25,7 +25,7 @@ jobs:
         with:
           dotnet-version: 7.x
 
-      - name: Generate executables
+      - name: Generate executable
         run: |
           Set-StrictMode -Version Latest
           $ErrorActionPreference = "Stop"
@@ -33,155 +33,192 @@ jobs:
           $InformationPreference = "Continue"
 
           Write-Information "Generating extractor..."
-          $extractorPath = Join-Path ${{ github.workspace }} "tools" "code" "extractor" "extractor.csproj"
-          & dotnet publish $extractorPath --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o extractor
+          $sourcePath = Join-Path ${{ github.workspace }} "tools" "code" "extractor" "extractor.csproj"
+          $outputDirectory = Join-Path ${{ runner.temp }} "extractor.{{ matrix.dotnet-runtime }}"
+          & dotnet publish $extractorPath --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true --output $outputDirectory
           if ($LASTEXITCODE -ne 0) { throw "Generating extractor failed."}
 
-          Write-Information "Generating publisher..."
-          $publisherPath = Join-Path ${{ github.workspace }} "tools" "code" "publisher" "publisher.csproj"
-          & dotnet publish $publisherPath --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o publisher
-          if ($LASTEXITCODE -ne 0) { throw "Generating publisher failed."}
-
-          Write-Information "Execution complete."
-        shell: pwsh
-
-      - name: Update versions in YAML
-        run: |
-          Set-StrictMode -Version Latest
-          $ErrorActionPreference = "Stop"
-          $VerbosePreference = "Continue"
-          $InformationPreference = "Continue"
-
-          $runExtractorPath = Join-Path ${{ github.workspace }} "tools" "github_workflows" "run-extractor.yaml"
-          (Get-Content -Path $runExtractorPath) |
-            ForEach-Object {$_ -Replace 'desired-version-goes-here', '${{ github.event.inputs.Release_Version }}'} |
-              Set-Content -Path $runExtractorPath
-
-          $runPublisherWithEnvPath = Join-Path ${{ github.workspace }} "tools" "github_workflows" "run-publisher-with-env.yaml"
-          (Get-Content -Path $runExtractorPath) |
-            ForEach-Object {$_ -Replace 'desired-version-goes-here', '${{ github.event.inputs.Release_Version }}'} |
-              Set-Content -Path $runPublisherWithEnvPath
-
-          Write-Information "Execution complete."
-        shell: pwsh
-
-      # - name: Generate executables
-      #   run: |
-      #     set -euxo pipefail
-
-      #     echo "Generating extractor..."
-      #     dotnet publish ${{ github.workspace }}/tools/code/extractor/extractor.csproj --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o extractor
-
-      #     echo "Generating publisher..."
-      #     dotnet publish ${{ github.workspace }}/tools/code/publisher/publisher.csproj --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o publisher
-
-      #     echo "Execution complete."
-      #   shell: bash
-
-      # - name: Replace versions in YAML
-      #   run: |
-      #     set -euxo pipefail
-
-      #     sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' ${{ github.workspace }}/tools/github_workflows/run-extractor.yaml
-      #     sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' ${{ github.workspace }}/tools/github_workflows/run-publisher-with-env.yaml
-
-      #     echo "Execution complete."
-      #   shell: bash
-# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: "extractor.{{ matrix.dotnet-runtime }}"
+          path: ${{ runner.temp }}/extractor.{{ matrix.dotnet-runtime }}
 # jobs:
-#   # This workflow contains a single job called "build"
-#   Generate_Artifacts:
+#   generate_artifacts:
+#     name: Generate artifacts
 #     strategy:
 #       matrix:
 #         dotnet-runtime: [linux-x64, win-x64]
-#     # The type of runner that the job will run on
-#     runs-on: ${{ fromJson(os-parameters).(matrix.dotnet-runtime).runs-on }}
-#     env:
-#       os-parameters: |
-#         {
-#           "linux-x64":{
-#             "runs-on":"ubuntu-latest"
-#           },
-#           "win-x64":{
-#             "runs-on":"windows-latest"
-#           }
-#         }
-
-#     # Steps represent a sequence of tasks that will be executed as part of the job
+#     # Dynamically set the runner OS based on the .NET runtime
+#     runs-on: ${{ fromJSON('{"linux-x64":"ubuntu-latest", "win-x64":"windows-latest"}')[matrix.dotnet-runtime] }}
 #     steps:
-#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#       - uses: actions/checkout@v2
+#       - name: Checkout repository
+#         uses: actions/checkout@v2
 
 #       - name: Setup .NET
 #         uses: actions/setup-dotnet@v1
 #         with:
 #           dotnet-version: 7.x
-#           include-prerelease: true
 
-#       - name: Generate Artifacts
+#       - name: Generate
+
+#       - name: Generate executables
 #         run: |
-#           #generate the extractor binary
-#           cd tools/code/extractor/
-#           dotnet publish ./extractor.csproj --self-contained --runtime linux-x64 -p:PublishSingleFile=true -o extractor
+#           Set-StrictMode -Version Latest
+#           $ErrorActionPreference = "Stop"
+#           $VerbosePreference = "Continue"
+#           $InformationPreference = "Continue"
 
-#           #go back to the root of the workspace
-#           cd ${{github.workspace}}
+#           Write-Information "Generating extractor..."
+#           $extractorPath = Join-Path ${{ github.workspace }} "tools" "code" "extractor" "extractor.csproj"
+#           & dotnet publish $extractorPath --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o extractor
+#           if ($LASTEXITCODE -ne 0) { throw "Generating extractor failed."}
 
-#           #generate the publisher binary
-#           cd tools/code/publisher/
-#           dotnet publish ./publisher.csproj --self-contained --runtime linux-x64 -p:PublishSingleFile=true -o publisher
+#           Write-Information "Generating publisher..."
+#           $publisherPath = Join-Path ${{ github.workspace }} "tools" "code" "publisher" "publisher.csproj"
+#           & dotnet publish $publisherPath --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o publisher
+#           if ($LASTEXITCODE -ne 0) { throw "Generating publisher failed."}
 
-#           # replace the the release version in extractor and publisher of the github pipelines. Azure devops pipelines aren't affected
-#           cd ${{github.workspace}}/tools/github_workflows/
-#           sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' run-extractor.yaml
-#           sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' run-publisher-with-env.yaml
+#           Write-Information "Execution complete."
+#         shell: pwsh
 
-#       - name: Package the artifacts
+#       - name: Update versions in YAML
 #         run: |
-#           #go back to the root of the workspace
-#           cd ${{github.workspace}}
-#           mkdir finalartifacts
-#           cd finalartifacts
-#           mkdir -p tools/pipelines
-#           mkdir -p tools/utils
-#           mkdir -p .github/workflows
-#           # this will ensure the right directory structure in the zipped packages when released on github
-#           cp ${{github.workspace}}/tools/azdo_pipelines/*.yaml tools/pipelines
-#           cp ${{github.workspace}}/tools/utils/* tools/utils
-#           cp ${{github.workspace}}/tools/github_workflows/*.yaml .github/workflows
-#           cp -r ${{github.workspace}}/tools/code/extractor/extractor/extractor .
-#           cp -r ${{github.workspace}}/tools/code/publisher/publisher/publisher .
-#           #create a package for the azure devops users
-#           zip Azure_DevOps.zip tools/pipelines/*.yaml tools/utils/create_pull_request.sh
-#           #create a package for the Github users
-#           zip Github.zip .github/workflows/*.yaml
-#           #carry cleanup before publishing
-#           rm -R tools
-#           rm -R .github
+#           Set-StrictMode -Version Latest
+#           $ErrorActionPreference = "Stop"
+#           $VerbosePreference = "Continue"
+#           $InformationPreference = "Continue"
 
-#       - name: publish artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#           name: artifacts
-#           path: ${{ GITHUB.WORKSPACE }}/finalartifacts
+#           $runExtractorPath = Join-Path ${{ github.workspace }} "tools" "github_workflows" "run-extractor.yaml"
+#           (Get-Content -Path $runExtractorPath) |
+#             ForEach-Object {$_ -Replace 'desired-version-goes-here', '${{ github.event.inputs.Release_Version }}'} |
+#               Set-Content -Path $runExtractorPath
 
-#   Generate_Release:
-#    needs: Generate_Artifacts
-#    runs-on: [ubuntu-latest]
-#    steps:
-#    - name: Download artifacts
-#      uses: actions/download-artifact@v2
-#      with:
-#        name: artifacts
-#        path: ${{ GITHUB.WORKSPACE }}/finalartifacts
-#    - name: Release
-#      uses: softprops/action-gh-release@v1
-#      with:
-#        files: |
-#          ${{github.workspace}}/finalartifacts/extractor
-#          ${{github.workspace}}/finalartifacts/publisher
-#          ${{github.workspace}}/finalartifacts/Azure_DevOps.zip
-#          ${{github.workspace}}/finalartifacts/Github.zip
-#        name: APIOps Toolkit for Azure APIM ${{ github.event.inputs.Release_Version }}
-#        tag_name: ${{ github.event.inputs.Release_Version }}
-#        generate_release_notes: true
+#           $runPublisherWithEnvPath = Join-Path ${{ github.workspace }} "tools" "github_workflows" "run-publisher-with-env.yaml"
+#           (Get-Content -Path $runExtractorPath) |
+#             ForEach-Object {$_ -Replace 'desired-version-goes-here', '${{ github.event.inputs.Release_Version }}'} |
+#               Set-Content -Path $runPublisherWithEnvPath
+
+#           Write-Information "Execution complete."
+#         shell: pwsh
+
+#       # - name: Generate executables
+#       #   run: |
+#       #     set -euxo pipefail
+
+#       #     echo "Generating extractor..."
+#       #     dotnet publish ${{ github.workspace }}/tools/code/extractor/extractor.csproj --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o extractor
+
+#       #     echo "Generating publisher..."
+#       #     dotnet publish ${{ github.workspace }}/tools/code/publisher/publisher.csproj --self-contained --runtime ${{ matrix.dotnet-runtime }} -p:PublishSingleFile=true -o publisher
+
+#       #     echo "Execution complete."
+#       #   shell: bash
+
+#       # - name: Replace versions in YAML
+#       #   run: |
+#       #     set -euxo pipefail
+
+#       #     sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' ${{ github.workspace }}/tools/github_workflows/run-extractor.yaml
+#       #     sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' ${{ github.workspace }}/tools/github_workflows/run-publisher-with-env.yaml
+
+#       #     echo "Execution complete."
+#       #   shell: bash
+# # # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# # jobs:
+# #   # This workflow contains a single job called "build"
+# #   Generate_Artifacts:
+# #     strategy:
+# #       matrix:
+# #         dotnet-runtime: [linux-x64, win-x64]
+# #     # The type of runner that the job will run on
+# #     runs-on: ${{ fromJson(os-parameters).(matrix.dotnet-runtime).runs-on }}
+# #     env:
+# #       os-parameters: |
+# #         {
+# #           "linux-x64":{
+# #             "runs-on":"ubuntu-latest"
+# #           },
+# #           "win-x64":{
+# #             "runs-on":"windows-latest"
+# #           }
+# #         }
+
+# #     # Steps represent a sequence of tasks that will be executed as part of the job
+# #     steps:
+# #       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+# #       - uses: actions/checkout@v2
+
+# #       - name: Setup .NET
+# #         uses: actions/setup-dotnet@v1
+# #         with:
+# #           dotnet-version: 7.x
+# #           include-prerelease: true
+
+# #       - name: Generate Artifacts
+# #         run: |
+# #           #generate the extractor binary
+# #           cd tools/code/extractor/
+# #           dotnet publish ./extractor.csproj --self-contained --runtime linux-x64 -p:PublishSingleFile=true -o extractor
+
+# #           #go back to the root of the workspace
+# #           cd ${{github.workspace}}
+
+# #           #generate the publisher binary
+# #           cd tools/code/publisher/
+# #           dotnet publish ./publisher.csproj --self-contained --runtime linux-x64 -p:PublishSingleFile=true -o publisher
+
+# #           # replace the the release version in extractor and publisher of the github pipelines. Azure devops pipelines aren't affected
+# #           cd ${{github.workspace}}/tools/github_workflows/
+# #           sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' run-extractor.yaml
+# #           sed -i 's/desired-version-goes-here/${{ github.event.inputs.Release_Version }}/g' run-publisher-with-env.yaml
+
+# #       - name: Package the artifacts
+# #         run: |
+# #           #go back to the root of the workspace
+# #           cd ${{github.workspace}}
+# #           mkdir finalartifacts
+# #           cd finalartifacts
+# #           mkdir -p tools/pipelines
+# #           mkdir -p tools/utils
+# #           mkdir -p .github/workflows
+# #           # this will ensure the right directory structure in the zipped packages when released on github
+# #           cp ${{github.workspace}}/tools/azdo_pipelines/*.yaml tools/pipelines
+# #           cp ${{github.workspace}}/tools/utils/* tools/utils
+# #           cp ${{github.workspace}}/tools/github_workflows/*.yaml .github/workflows
+# #           cp -r ${{github.workspace}}/tools/code/extractor/extractor/extractor .
+# #           cp -r ${{github.workspace}}/tools/code/publisher/publisher/publisher .
+# #           #create a package for the azure devops users
+# #           zip Azure_DevOps.zip tools/pipelines/*.yaml tools/utils/create_pull_request.sh
+# #           #create a package for the Github users
+# #           zip Github.zip .github/workflows/*.yaml
+# #           #carry cleanup before publishing
+# #           rm -R tools
+# #           rm -R .github
+
+# #       - name: publish artifact
+# #         uses: actions/upload-artifact@v2
+# #         with:
+# #           name: artifacts
+# #           path: ${{ GITHUB.WORKSPACE }}/finalartifacts
+
+# #   Generate_Release:
+# #    needs: Generate_Artifacts
+# #    runs-on: [ubuntu-latest]
+# #    steps:
+# #    - name: Download artifacts
+# #      uses: actions/download-artifact@v2
+# #      with:
+# #        name: artifacts
+# #        path: ${{ GITHUB.WORKSPACE }}/finalartifacts
+# #    - name: Release
+# #      uses: softprops/action-gh-release@v1
+# #      with:
+# #        files: |
+# #          ${{github.workspace}}/finalartifacts/extractor
+# #          ${{github.workspace}}/finalartifacts/publisher
+# #          ${{github.workspace}}/finalartifacts/Azure_DevOps.zip
+# #          ${{github.workspace}}/finalartifacts/Github.zip
+# #        name: APIOps Toolkit for Azure APIM ${{ github.event.inputs.Release_Version }}
+# #        tag_name: ${{ github.event.inputs.Release_Version }}
+# #        generate_release_notes: true
